name: Docker Imgane CI

on:
  push:
    branches: ['main']


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Login to to Dockerhub
        env: 
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker Image
        run: docker build -t user2103/garbage-detection-app:${{vars.VERSION}} .

      - name: Push to Dockerhub
        run: docker push user2103/garbage-detection-app:${{vars.VERSION}}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOST_IP }} 
          username: "ubuntu"
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull user2103/garbage-detection-app:${{vars.VERSION}}
            docker stop garbage-detection-app || true
            docker rm garbage-detection-app || true
            docker run -d --name garbage-detection-app -p 2103:8501 user2103/garbage-detection-app:${{vars.VERSION}}
            docker image prune -a -f

          
