name: Manual Deploy to EC2

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'ระบุ Version (เช่น v1.0)'
        required: true
        default: 'latest'
      host:
        description: 'ระบุ host ip'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ inputs.host }}
          username: "ubuntu"
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Deploying version: ${{ inputs.version }}"
            sudo docker pull user2103/garbage-detection-app:${{ inputs.version }}

            sudo docker run -d --name garbage-detection-app -p 2103:8501 user2103/garbage-detection-app:${{ inputs.version }}

            sudo docker stop garbage-detection-app || true
            sudo docker rm garbage-detection-app || true
            
            sudo docker image prune -a -f
